keigomichi/tsundokun

- app/build.gradle
- app/src/main/java/com/example/tsundoku/MainActivity.kt
- app/src/main/java/com/example/tsundoku/ui/add_tsundoku/AddTsundokuScreen.kt
- app/src/main/java/com/example/tsundoku/ui/home/HomeScreen.kt
- build.gradle
- Close #6
- [Compose Destination](https://composedestinations.rafaelcosta.xyz) を追加
- kspを追加 & Gradle 8.0でのエラー解消
- ホーム画面と積読追加画面用の空のComposableを作成
```
[x] Yes
[ ] No
```
-
> feat: 画面遷移を実装

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/dictionaries/tsundokuDictionary.xml
- .idea/dictionaries/tsundokunDictionary.xml
- app/build.gradle.kts
- app/src/androidTest/java/com/example/tsundokun/ExampleInstrumentedTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/tsundokun/MainActivity.kt
- app/src/main/java/com/example/tsundokun/ui/add_tsundoku/AddTsundokuScreen.kt
- app/src/main/java/com/example/tsundokun/ui/home/HomeScreen.kt
- app/src/main/java/com/example/tsundokun/ui/theme/Color.kt
- app/src/main/java/com/example/tsundokun/ui/theme/Theme.kt
- app/src/main/java/com/example/tsundokun/ui/theme/Type.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/values/themes.xml
- app/src/test/java/com/example/tsundokun/ExampleUnitTest.kt
- settings.gradle
- Close #22
- `tsundoku` を `tsundokun` に修正しました。
```
[x] Yes
[ ] No
```
-
> refactor: tsundoku を tsundokun に修正

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- Close #21
- `libs.versions.toml` を作成し、`build.gradle.kts` 内を修正しました。
```
[x] Yes
[ ] No
```
-
> build: version catalogsを導入

- settings.gradle.kts
- Close #19
- `settings.gradle` を変え忘れていたので、修正
```
[x] Yes
[ ] No
```
-
> refactor: settings.gradleをktsに移行

- .github/ci-gradle.properties
- .github/workflows/build.yml
- .github/workflows/format-suggestion.yml
- Close #34
```
[x] Yes
[ ] No
```
-
> ci: build用のworkflowを追加

- .github/workflows/build.yml
- app/.gitignore
- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- Close #30 
```
[ ] Yes
[ ] No
```
-
> feat:firebaseを追加

- app/build.gradle.kts
- build.gradle.kts
- gradle/libs.versions.toml
- Close #3 
supabaseの環境構築に必要なモジュールをインストールしました
可能です！
```
[x] Yes
[ ] No
```
-
> chore: supabase環境構築

- .github/workflows/build.yml
- Close #
```
[x] Yes
[ ] No
```
-
> ci: developへのpushでbuildのciが走るように

- app/src/main/java/com/example/tsundokun/ui/home/HomeScreen.kt
- app/src/main/java/com/example/tsundokun/ui/setting/SettingScreen.kt
- Close #13
設定画面のuiを作成しました
```
[x] Yes
[ ] No
```
-
> feat: 設定画面のui作成

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/tsundokun/MainActivity.kt
- app/src/main/java/com/example/tsundokun/ui/stack/StackScreen.kt
- #59 
- WebブラウザからURLをアプリに共有できるようにしました
```
[×] Yes
[ ] No
```
[アプリ画面の動画](https://github.com/keigomichi/tsundokun/assets/77912477/5fd0c1d8-09b8-4cce-9286-4694287ea048)
> WebブラウザからURLをアプリに共有できるようにする

- app/build.gradle.kts
- app/src/main/java/com/example/tsundokun/MainActivity.kt
- app/src/main/res/values/strings.xml
- Close #31 
```
[x] Yes
[ ] No
```
-
> feat: 更新ダイアログを表示

- .github/workflows/label-approved-pull-requests.yml
- Close #
```
[x] Yes
[ ] No
```
-
> ci: add Label approved pull requests

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/tsundokun/MainActivity.kt
- app/src/main/java/com/example/tsundokun/TsundokuApplication.kt
- app/src/main/java/com/example/tsundokun/data/local/DatabaseModule.kt
- gradle/libs.versions.toml
- Close #16
```
[x] Yes
[ ] No
```
-
> feat: Hiltを導入

- renovate.json
- Close #
```
[x] Yes
[ ] No
```
-
> chore: add label to renovate pr

- app/src/androidTest/java/com/example/tsundokun/TsundokuDaoTest.kt
- app/src/main/java/com/example/tsundokun/data/local/DatabaseModule.kt
- app/src/main/java/com/example/tsundokun/data/local/TsundokunDatabase.kt
- app/src/main/java/com/example/tsundokun/data/local/dao/CategoryDao.kt
- app/src/main/java/com/example/tsundokun/data/local/dao/TsundokuDao.kt
- app/src/main/java/com/example/tsundokun/data/local/entities/CategoryEntity.kt
- app/src/main/java/com/example/tsundokun/data/local/entities/TsundokuCategoryEntity.kt
- app/src/main/java/com/example/tsundokun/data/local/entities/TsundokuEntity.kt
- Close #
```
[x] Yes
[ ] No
```
-
> refactor: refactor local datasource

- app/src/main/java/com/example/tsundokun/ui/home/HomeScreen.kt
- app/src/main/res/values/strings.xml
- Close #79 
```
[x] Yes
[ ] No
```
-
> feat: ホーム画面からの共有機能

- app/src/main/java/com/example/tsundokun/ui/confirm/ConfirmScreen.kt
- app/src/main/java/com/example/tsundokun/ui/confirm/ConfirmViewModel.kt
- app/src/main/java/com/example/tsundokun/ui/home/HomeScreen.kt
- app/src/main/java/com/example/tsundokun/ui/home/HomeViewmodel.kt
- Close #
```
[ ] Yes
[ ] No
```
-
> feat: ホーム画面につんどく表示

- .github/workflows/staging.yaml
- Close #
```
[x] Yes
[ ] No
```
-
> ci: add firebase app distribution workflow

- .github/workflows/staging.yaml
- Close #
```
[ ] Yes
[ ] No
```
-
> fix: `staging.yml` - copy google-service

- .github/workflows/staging.yaml
- Close #
```
[ ] Yes
[ ] No
```
-
> fix: `staging.yml` - add option

- app/src/main/java/com/example/tsundokun/ui/setting/SettingScreen.kt
- app/src/main/java/com/example/tsundokun/ui/setting/SettingViewmodel.kt
- app/src/main/java/com/example/tsundokun/ui/setting/component/DeleteDialog.kt
- Close #13
結果待ち暇だったので設定画面にデータを全部吹き飛ばすボタン作りました
```
[x] Yes
[ ] No
```
-
> add: 全データの削除ボタンの追加
